// Library imports.
const mongoose = require('mongoose');
const sha256 = require('js-sha256');

// Custom imports.
const configJson = require('../config.json');
const db = require('../db');
const Article = require('../db/models/article');
const Page = require('../db/models/page');
const User = require('../db/models/user');

// Constants
const secretKey = configJson.secretKey;

db.once('open', function () {
  // Wipe old database first.
  console.log('Dropping database.');
  mongoose.connection.db.dropDatabase();

  new User({
    name: 'Alex Karino',
    username: 'alex',
    password: sha256('password' + secretKey),
    isAdmin: true,
  }).save((err, obj) => { err ? console.log(err) : console.log('User ' + obj.name + ' created.'); });

  new User({
    name: 'Bob Marley',
    username: 'bob',
    password: sha256('password' + secretKey)
  }).save((err, obj) => { err ? console.log(err) : console.log('User ' + obj.name + ' created.'); });

  new User({
    name: 'Cave Johnson',
    username: 'cave',
    password: sha256('password' + secretKey)
  }).save((err, obj) => { err ? console.log(err) : console.log('User ' + obj.name + ' created.'); });

  new Article({
    _id: 'my-first-article',
    title: 'My First Article',
    subtitle: 'Kicking off my blog with an awesome new subtitle.',
    author: 'cave',
    body: 'Flannel etsy yuccie artisan kale chips. Drinking vinegar XOXO cray, jianbing roof party blog narwhal pug vice tilde paleo coloring book meggings chambray. Shabby chic kitsch mumblecore, snackwave health goth raclette everyday carry. Knausgaard enamel pin tote bag biodiesel PBR&B hammock unicorn, literally green juice. Bespoke mumblecore brooklyn schlitz neutra, DIY tbh kombucha hella hell of gastropub. Next level edison bulb four loko fanny pack art party, vice prism poke. Knausgaard mixtape four dollar toast intelligentsia iPhone seitan.',
    isPublished: true
  }).save((err, obj) => { err ? console.log(err) : console.log('Article ' + obj.title + ' created.'); });

  new Article({
    _id: 'unlucky',
    title: 'Unlucky',
    subtitle: 'Because things can happen.',
    author: 'bob',
    body: 'Intelligentsia pop-up raw denim, occupy fanny pack leggings cornhole. Craft beer pitchfork occupy raclette pork belly. Enamel pin iceland forage kale chips, bicycle rights unicorn fixie. Yr 3 wolf moon edison bulb marfa taxidermy hella, poutine forage VHS keytar retro typewriter live-edge. Bitters la croix williamsburg viral PBR&B, tousled YOLO +1 hoodie locavore marfa everyday carry meh unicorn gastropub. Slow-carb four loko tofu, 90\'s health goth unicorn stumptown readymade. Franzen cray humblebrag seitan kinfolk, typewriter scenester bicycle rights bespoke kale chips kitsch ramps.',
    isPublished: true
  }).save((err, obj) => { err ? console.log(err) : console.log('Article ' + obj.title + ' created.'); });

  new Article({
    _id: 'my-favorite-snacks-from-2016',
    title: 'My Favorite Snacks from 2016',
    subtitle: 'What\'s wrong with having a few cheat days, or a lot?',
    author: 'cave',
    body: 'Aesthetic tbh truffaut synth wayfarers gochujang. Ennui portland distillery small batch direct trade, art party pickled jean shorts fanny pack truffaut poke prism affogato typewriter. Butcher banh mi tofu, drinking vinegar green juice fap street art jean shorts subway tile swag godard pabst mlkshk 3 wolf moon. Polaroid whatever taxidermy gochujang twee crucifix. Shabby chic etsy cornhole, locavore ennui street art taxidermy echo park wayfarers fanny pack skateboard vinyl. Meggings leggings cliche narwhal chillwave, cold-pressed retro. IPhone gastropub tbh, cray thundercats mlkshk four loko tilde tumeric pug ramps tofu.',
    isPublished: true
  }).save((err, obj) => { err ? console.log(err) : console.log('Article ' + obj.title + ' created.'); });

  new Article({
    _id: 'this-is-last-article',
    title: 'This is the last article.',
    subtitle: 'That gets generated by the population script.',
    author: 'cave',
    body: 'Lumbersexual jianbing lo-fi, fam hoodie everyday carry hella tumeric intelligentsia artisan literally pabst thundercats ugh echo park. Poutine narwhal photo booth gluten-free, fingerstache kale chips tumblr portland butcher. Blog copper mug craft beer jean shorts seitan. PBR&B lo-fi mlkshk hammock, iceland subway tile taxidermy sartorial fixie cold-pressed post-ironic freegan blue bottle keytar mustache. Bushwick gastropub polaroid church-key messenger bag coloring book. Fam schlitz flannel man braid polaroid snackwave. Ennui chambray plaid tousled cray typewriter, hella kombucha tilde edison bulb tofu shoreditch.',
    isPublished: false
  }).save((err, obj) => { err ? console.log(err) : console.log('Article ' + obj.title + ' created.'); });

  new Page({
    _id: 'most-overplayed-songs-of-my-playlist-2009',
    title: 'The Most Overplayed Songs of My Playlist 2009.',
    subtitle: 'Because you want to know too.',
    author: 'alex',
    body: 'Authentic banjo cornhole fixie gochujang vape. Man bun slow-carb gluten-free wayfarers, gentrify tumblr lyft thundercats squid affogato austin biodiesel sriracha quinoa post-ironic. Listicle celiac snackwave, pok pok food truck pop-up hella health goth occupy tofu art party chartreuse. Humblebrag vinyl viral fixie, tattooed street art semiotics hoodie vaporware jean shorts pour-over. Tacos butcher freegan swag slow-carb, tumblr fap literally four loko bicycle rights. Cronut godard pok pok, green juice snackwave banjo portland semiotics forage photo booth. Heirloom keffiyeh tote bag mixtape.',
    isPublished: true
  }).save((err, obj) => { err ? console.log(err) : console.log('Page ' + obj.title + ' created.'); });

  new Page({
    _id: 'collection-of-pirated-games-with-no-download-links',
    title: 'Collection of Pirated Games With No Download Links',
    subtitle: 'Literally a clickbait so move on.',
    author: 'cave',
    body: 'Echo park lomo cliche, offal blue bottle meggings hashtag kombucha VHS iPhone wayfarers street art. Edison bulb polaroid retro vaporware, drinking vinegar schlitz vegan viral kogi coloring book aesthetic small batch pok pok. Blue bottle 90\'s neutra, +1 deep v williamsburg authentic dreamcatcher slow-carb DIY. Freegan pickled umami paleo gochujang air plant YOLO, activated charcoal edison bulb narwhal salvia la croix affogato heirloom. Beard keffiyeh waistcoat scenester migas, cronut direct trade. Ugh etsy swag beard woke, everyday carry seitan raw denim echo park schlitz franzen. Affogato semiotics irony fashion axe before they sold out, distillery lyft meditation.',
    isPublished: true
  }).save((err, obj) => { err ? console.log(err) : console.log('Page ' + obj.title + ' created.'); });
});
